config/routes.rb
Rails.application.routes.draw do
  concern :with_datatable do
    post :datatable, on: :collection
  end
  resources :group_users
  resources :groups do
    post :invite_member, on: :collection
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    collection do
      post :accept_membership
      post :decline_membership
      post :cancel_membership
      post :remove_from_group
      post :cancel_invitation
      post :block_membership
      post :block_user
      post :toggle_admin
      post :transfer_ownership
    end
  end
  get 'home/index'
  resources :occurrences
  resources :recurrence_rules
  resources :payments
  resources :accounts
  resources :transfers
  resources :transaction_purposes do
    get :display_recurrence_rule_text, on: :collection
  end
  resources :transactions
  resources :sub_categories
  resources :categories
  resources :account_balances
  resources :home
  resource :summary
  root to: 'home#index'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :expenses, as: :owner
  has_many :group_users
  has_many :users, through: :group_users
  has_many :accounts, through: :group_users
  has_many :transaction_purposes, through: :group_users
  has_many :transactions, through: :group_users
  has_many :transfers, through: :group_users
  has_many :payments, through: :group_users
  has_many :occurrences, through: :group_users

  validates :name, presence: true

  def invite(member) # send_request
    self.group_users.where(user: member, status: :invited).first_or_create!
  end

  def request(member) # request to join
    self.group_users.where(user: member, status: :requested).first_or_create!
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :invite_member]

  def index
    @groups = current_user.groups
  end

  def new
    @group = current_user.group.new
    render layout: false
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      render_failure(@group)
    end
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: 'Group was successfully updated.'
    else
      render_failure(@group)
    end
  end

  def destroy
    if @group.destroy
      redirect_to groups_path, notice: 'Group was successfully destroyed.'
    else
      redirect_to groups_path, notice: 'Group could not be destroyed.'
    end
  end

  def invite_member
    user = User.search(params[:search_term])
    if user
      if @group.invite(user)
        flash[:notice] = 'Member invited successfully'
      else
        flash[:error] = "Failed to invite member. #{@group.errors.full_messages.to_sentence}"
      end
    else
      flash[:error] = 'User not found.'
      # TODO : Implement invitable and while joining join with group invitation
      # Implement this after friendlyId is implemented
      # Check if the link is opened by intended user, else create record with status as requested
    end
    redirect_to groups_path
  end

  private
    def set_group
      @group = current_user.groups.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :default)
    end
end

app/views/groups/_form.html.haml
= form_with(model: object, remote: true) do |f|
  - if object.errors.any?
    #error_explanation
      %p= "#{pluralize(object.errors.count, "error")} prohibited this Group from being saved:"
      %ul
        - object.errors.full_messages.each do |message|
          %li= message
  .row
    = f.label :name
    = f.text_field :name
  - if current_user.admin?
    .row
      = f.label :default
      = f.check_box :default
  = render 'shared/timestamps', f: f # TODO: Add this partial to generator
  = render 'shared/reveal_footer', f: f # TODO: Add this partial to generator

app/views/groups/_index_for_admins.html.haml
%h1
  Groups
  = add_new_button('Add New Group', new_group_path)

.table-scroll
  %table.striped.hover.table-striped.stack
    %thead
      %tr
        %th Id
        %th Owner
        %th Name
        %th Default
        %th Created at
        %th Updated at
        %th Actions

    %tbody
      - if @groups.present?
        - @groups.each do |group|
          %tr
            %td= group.id
            %td= group.owner.name
            %td= group.name
            %td= group.default
            %td= group.created_at
            %td= group.updated_at
            %td= render 'shared/table_row_action_buttons', object: group
      - else
        %tr
          %td.text-center{colspan: 7}= 'No records found'

app/views/groups/_index_for_non_admins.html.haml
%h1
  My Groups
  = add_new_button('Add New Group', new_group_path)

.table-scroll
  %table.striped.hover.table-striped.stack
    %thead
      %tr
        %th Name
        %th Owner
        %th Actions

    %tbody
      - if @groups.present?
        - @groups.each do |group|
          %tr
            %td= group.name
            %td= group.owner.name
            %td
              .button-group
                = link_to_edit_icon(group)
                = link_to_reveal "#{group.group_users.count} Members", group_path(group), 'button success'
                - if !group.default? && current_user.group_owner_for?(group)
                  = link_to_delete_icon(group)
      - else
        %tr
          %td.text-center{colspan: 3}= 'No records found'

app/views/groups/edit.html.haml
%h1= "Editing Group: ##{@group.id}"

= render 'form', object: @group

app/views/groups/index.html.haml
- if current_user.admin?
  = render 'index_for_admins'
- else
  = render 'index_for_non_admins'

app/views/groups/new.html.haml
%h1 New Group

= render 'form', object: @group

app/views/groups/show.html.haml
- if current_user.admin?
  .row
    %strong Id:
    = @group.id
  .row
    %strong Default:
    = @group.default
  .row
    %strong Created at:
    = @group.created_at
  .row
    %strong Updated at:
    = @group.updated_at
.row
  %strong Name:
  = @group.name
.row
  %strong Owner:
  = @group.owner.name
.row
  = link_to_edit(@group)
  = close_reveal_button
%hr
.row
  %strong Members:
.row
  = form_with url: invite_member_groups_path, method: :post, remote: true do |f|
    .input-group
      = f.text_field :search_term, placeholder: 'Enter email or username', class: 'input-group-field'
      = f.hidden_field :id, value: @group.id
      .input-group-button= f.submit 'Invite to join group', class: 'button primary'
.row
  = invite_for_registration_via_whatsapp
  .help-text
    = 'Note : ' #icon_tag 'info'
    = 'You need to have WhatsApp application or WhatsApp web setup on your device.'


.row
  %table.striped.hover.table-striped.stack
    %thead
      %tr
        %th User
        %th Status
        %th Actions
    %tbody
      - @group.users.each do |user|
        %tr
          %td= user.name
          %td= @group.owner == user ? 'Owner' : @group.group_users.find_by(user_id: user.id).try(:status)
          %td
            - if @group.owner == current_user
              - unless @group.default?
                = link_to 'Delete Group', group, method: :delete, data: { confirm: 'Are you sure you want to delete this Group?' }, class: 'button alert'
              - if user != current_user && @group.group_users.find_by(user_id: user.id).accepted?
                = form_with url: transfer_ownership_users_path, method: :post, remote: true do |f|
                  = f.hidden_field :id, value: user.id
                  = f.hidden_field :group_id, value: @group.id
                  = f.submit 'Transfer Ownership', class: 'button primary small'
            - if current_user != user
              - if current_user.group_admin_for?(@group) && !user.group_owner_for?(@group)
                - if @group.group_users.find_by(user_id: user.id).accepted?
                  = form_with url: toggle_admin_users_path, method: :post, remote: true do |f|
                    = f.hidden_field :id, value: user.id
                    = f.hidden_field :group_id, value: @group.id
                    = f.submit "#{user.group_admin_for?(@group) ? 'Remove' : 'Make'} Admin", class: 'button primary small'
                - if @group.group_users.find_by(user_id: user.id).requested?
                  = form_with url: accept_membership_users_path, method: :post, remote: true do |f|
                    = f.hidden_field :id, value: user.id
                    = f.hidden_field :group_id, value: @group.id
                    = f.submit 'Accept Request', class: 'button primary small'
                  = form_with url: decline_membership_users_path, method: :post, remote: true do |f|
                    = f.hidden_field :id, value: user.id
                    = f.hidden_field :group_id, value: @group.id
                    = f.submit 'Decline Request', class: 'button primary small'
                  = form_with url: block_user_users_path, method: :post, remote: true do |f|
                    = f.hidden_field :id, value: user.id
                    = f.hidden_field :group_id, value: @group.id
                    = f.submit 'Block User', class: 'button primary small'
                - if @group.group_users.find_by(user_id: user.id).invited?
                  = form_with url: cancel_invitation_users_path, method: :post, remote: true do |f|
                    = f.hidden_field :id, value: user.id
                    = f.hidden_field :group_id, value: @group.id
                    = f.submit 'Cancel Invitation', class: 'button primary small'
                - if @group.group_users.find_by(user_id: user.id).accepted?
                  = form_with url: remove_from_group_users_path, method: :post, remote: true do |f|
                    = f.hidden_field :id, value: user.id
                    = f.hidden_field :group_id, value: @group.id
                    = f.submit 'Remove from Group', class: 'button primary small'
            - else
              - if @group.group_users.find_by(user_id: user.id).invited?
                = form_with url: accept_membership_users_path, method: :post, remote: true do |f|
                  = f.hidden_field :id, value: user.id
                  = f.hidden_field :group_id, value: @group.id
                  = f.submit 'Join Group', class: 'button primary small'
                = form_with url: decline_membership_users_path, method: :post, remote: true do |f|
                  = f.hidden_field :id, value: user.id
                  = f.hidden_field :group_id, value: @group.id
                  = f.submit 'Decline to Join', class: 'button primary small'
                = form_with url: block_membership_users_path, method: :post, remote: true do |f|
                  = f.hidden_field :id, value: user.id
                  = f.hidden_field :group_id, value: @group.id
                  = f.submit 'Block Group', class: 'button primary small'
              - if @group.group_users.find_by(user_id: user.id).accepted?
                = form_with url: cancel_membership_users_path, method: :post, remote: true do |f|
                  = f.hidden_field :id, value: user.id
                  = f.hidden_field :group_id, value: @group.id
                  = f.submit 'Exit Group', class: 'button primary small'