config/routes.rb
Rails.application.routes.draw do
  concern :with_datatable do
    post :datatable, on: :collection
  end
  resources :group_users
  resources :groups do
    post :invite_member, on: :collection
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    collection do
      post :accept_membership
      post :decline_membership
      post :cancel_membership
      post :remove_from_group
      post :cancel_invitation
      post :block_membership
      post :block_user
      post :toggle_admin
      post :transfer_ownership
    end
  end
  get 'home/index'
  resources :occurrences
  resources :recurrence_rules
  resources :payments
  resources :accounts
  resources :transfers
  resources :transaction_purposes do
    get :display_recurrence_rule_text, on: :collection
  end
  resources :transactions
  resources :sub_categories
  resources :categories
  resources :account_balances
  resources :home
  resource :summary
  root to: 'home#index'
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :transaction_purposes, dependent: :restrict_with_error

  validates :name, presence: true

  def name_with_category
    "#{category.name}: #{name}"
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  def index
    @sub_categories = SubCategory.all
  end

  def new
    @sub_category = SubCategory.new
    render layout: false
  end

  def create
    @sub_category = SubCategory.new(sub_category_params)
    if @sub_category.save
      redirect_to sub_categories_path, notice: 'Sub category was successfully created.'
    else
      render_failure(@sub_category)
    end
  end

  def update
    if @sub_category.update(sub_category_params)
      redirect_to sub_categories_path, notice: 'Sub category was successfully updated.'
    else
      render_failure(@sub_category)
    end
  end

  def destroy
    if @sub_category.destroy
      redirect_to sub_categories_path, notice: 'Sub category was successfully destroyed.'
    else
      redirect_to sub_categories_path, notice: 'Sub category could not be destroyed.'
    end
  end

  private
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    def sub_category_params
      params.require(:sub_category).permit(:name, :category_id)
    end
end

app/views/sub_categories/_form.html.haml
= form_with(model: object, remote: true) do |f|
  - if object.errors.any?
    #error_explanation
      %p= "#{pluralize(object.errors.count, "error")} prohibited this sub_category from being saved:"
      %ul
        - object.errors.full_messages.each do |message|
          %li= message
  .row
    = f.label :name
    = f.text_field :name, id: :sub_category_name
  .row
    = f.label :category_id
    = f.collection_select :category_id, Category.all, :id, :name, id: :sub_category_category_id
  = render 'shared/timestamps', f: f
  = render 'shared/reveal_footer', f: f

app/views/sub_categories/edit.html.haml
%h1= "Editing Sub Category: ##{@sub_category.id}"

= render 'form', object: @sub_category

app/views/sub_categories/index.html.haml
%h1
  Sub Categories
  = add_new_button('Add New Sub Category', new_sub_category_path)

%table.striped.hover.table-striped.stack
  %thead
    %tr
      %th Id
      %th Name
      %th Category
      %th Created at
      %th Updated at
      %th Actions

  %tbody
    - if @sub_categories.present?
      - @sub_categories.each do |sub_category|
        %tr
          %td= sub_category.id
          %td= sub_category.name
          %td= sub_category.category.name
          %td= sub_category.created_at
          %td= sub_category.updated_at
          %td= render 'shared/table_row_action_buttons', object: sub_category
    - else
      %tr
        %td.text-center{colspan: 6}= 'No records found'

app/views/sub_categories/new.html.haml
%h1 New Sub Category

= render 'form', object: @sub_category

app/views/sub_categories/show.html.haml
.row
  %strong Id:
  = @sub_category.id
.row
  %strong Name:
  = @sub_category.name
.row
  %strong Category:
  = @sub_category.category.name
.row
  %strong Created at:
  = @sub_category.created_at
.row
  %strong Updated at:
  = @sub_category.updated_at
.row
  = link_to_edit(@sub_category)
  = close_reveal_button