config/routes.rb
Rails.application.routes.draw do
  concern :with_datatable do
    post :datatable, on: :collection
  end
  resources :group_users
  resources :groups do
    post :invite_member, on: :collection
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    collection do
      post :accept_membership
      post :decline_membership
      post :cancel_membership
      post :remove_from_group
      post :cancel_invitation
      post :block_membership
      post :block_user
      post :toggle_admin
      post :transfer_ownership
    end
  end
  get 'home/index'
  resources :occurrences
  resources :recurrence_rules
  resources :payments
  resources :accounts
  resources :transfers
  resources :transaction_purposes do
    get :display_recurrence_rule_text, on: :collection
  end
  resources :transactions
  resources :sub_categories
  resources :categories
  resources :account_balances
  resources :home
  resource :summary
  root to: 'home#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories, dependent: :destroy

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    render layout: false
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render_failure(@category)
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render_failure(@category)
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path, notice: 'Category was successfully destroyed.'
    else
      redirect_to categories_path, notice: 'Category could not be destroyed.'
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_form.html.haml
= form_with(model: object, remote: true) do |f|
  - if object.errors.any?
    #error_explanation
      %p= "#{pluralize(object.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - object.errors.full_messages.each do |message|
          %li= message
  .row
    = f.label :name
    = f.text_field :name, id: :category_name
  = render 'shared/timestamps', f: f
  = render 'shared/reveal_footer', f: f

app/views/categories/edit.html.haml
%h1= "Editing Category: ##{@category.id}"

= render 'form', object: @category

app/views/categories/index.html.haml
%h1
  Categories
  = add_new_button('Add New Category', new_category_path)

%table.striped.hover.table-striped.stack
  %thead
    %tr
      %th Id
      %th Name
      %th Created at
      %th Updated at
      %th Actions

  %tbody
    - if @categories.present?
      - @categories.each do |category|
        %tr
          %td= category.id
          %td= category.name
          %td= category.created_at
          %td= category.updated_at
          %td= render 'shared/table_row_action_buttons', object: category
    - else
      %tr
        %td.text-center{colspan: 5}= 'No records found'

app/views/categories/new.html.haml
%h1 New Category

= render 'form', object: @category

app/views/categories/show.html.haml
.row
  %strong Id:
  = @category.id
.row
  %strong Name:
  = @category.name
.row
  %strong Created at:
  = @category.created_at
.row
  %strong Updated at:
  = @category.updated_at
.row
  = link_to_edit(@category)
  = close_reveal_button