config/routes.rb
Rails.application.routes.draw do
  concern :with_datatable do
    post :datatable, on: :collection
  end
  resources :group_users
  resources :groups do
    post :invite_member, on: :collection
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    collection do
      post :accept_membership
      post :decline_membership
      post :cancel_membership
      post :remove_from_group
      post :cancel_invitation
      post :block_membership
      post :block_user
      post :toggle_admin
      post :transfer_ownership
    end
  end
  get 'home/index'
  resources :occurrences
  resources :recurrence_rules
  resources :payments
  resources :accounts
  resources :transfers
  resources :transaction_purposes do
    get :display_recurrence_rule_text, on: :collection
  end
  resources :transactions
  resources :sub_categories
  resources :categories
  resources :account_balances
  resources :home
  resource :summary
  root to: 'home#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  def index
    @transactions = current_scope.transactions
  end

  def new
    @transaction = current_user.transactions.new
    render layout: false
  end

  # TODO: Make this compatible for transcations/form
  # This action is called from home/index
  def create
    transaction = current_user.transactions.new(transaction_params)
    if transaction.save
      new_transaction = current_user.transactions.new
      new_transaction.payments.build
      flash[:success] = 'Transaction created successfully.'
      render :success, locals: { transaction: transaction, new_transaction: new_transaction, transacted_at: params[:transaction][:transacted_at] }
    else
      flash[:failure] = transaction.errors.full_messages.to_sentence
      render :failure, locals: { transaction: transaction } # TODO: Check n Remove locals
    end
  end

  # TODO: Make this compatible for transcations/form
  # This action is called from home/index
  def update
    if @transaction.update(transaction_params)
      flash[:success] = 'Transaction updated successfully.'
      render :success, locals: { transaction: @transaction, transacted_at: params[:transaction][:transacted_at] }
    else
      flash[:failure] = @transaction.errors.full_messages.to_sentence
      render :failure, locals: { transaction: @transaction }
    end
  end

  def destroy
    if @transaction.destroy
      redirect_to transactions_path, success: 'Transaction destroyed successfully.'
    else
      redirect_to transactions_path, failure: 'Transaction could not be destroyed.'
    end
  end

  private
    def set_transaction
      @transaction = current_user.transactions.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:amount, :description, :transaction_purpose_id, :transfer_id, :transacted_at, payments_attributes: {})
    end
end

app/views/transactions/_form.html.haml
= form_with(model: transaction, remote: true) do |f|
  - if transaction.errors.any?
    #error_explanation
      %p= "#{pluralize(transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - transaction.errors.full_messages.each do |message|
          %li= message
  .row
    = f.label :amount
    = f.amount_field :amount, id: :transaction_amount, currency: '&#8377;'
  .row
    = f.label :description
    = f.text_field :description, id: :transaction_description
  .row
    = f.label :transaction_purpose_id
    = f.collection_select :transaction_purpose_id, current_user.transaction_purposes, :id, :name, id: :transaction_transaction_purpose_id
  .row
    = f.label :transfer_id
    = f.collection_select :transfer_id, current_user.transfers, :id, :name, id: :transaction_transfer_id
  = render 'shared/timestamps', f: f
  = render 'shared/reveal_footer', f: f

app/views/transactions/edit.html.haml
%h1= "Editing Transaction: ##{@transaction.id}"

= render 'form', transaction: @transaction

app/views/transactions/failure.js.erb
$('<%= ".#{params[:transaction][:unique_id]}" %>').prev('.flash-message').remove();
$('<%= ".#{params[:transaction][:unique_id]}" %>').before('<%=j flash_messages %>');

app/views/transactions/index.html.haml
%h1
  Transactions
  = render 'shared/family_switch'
  = add_new_button('Add New Transaction', new_transaction_path)

%table.striped.hover.table-striped.stack
  %thead
    %tr
      - if current_user.admin?
        %th Id
      - if family_view?
        %th User
      %th Transaction purpose
      %th Description
      %th Amount
      - if current_user.admin?
        %th Created at
        %th Updated at
      %th Actions

  %tbody
    - if @transactions.present?
      - @transactions.each do |transaction|
        %tr
          - if current_user.admin?
            %td= transaction.id
          - if family_view?
            %td= transaction.user.name
          %td= transaction.transaction_purpose.name
          %td= transaction.description
          %td{ class: transaction.credit? ? 'text-success' : 'text-alert' }
            = transaction.sign
            = transaction.amount
          - if current_user.admin?
            %td= transaction.created_at
            %td= transaction.updated_at
          %td= render 'shared/table_row_action_buttons', object: transaction
    - else
      %tr
        %td.text-center{colspan: 8}= 'No records found'

app/views/transactions/new.html.haml
%h1 New Transaction

= render 'form', transaction: @transaction

app/views/transactions/show.html.haml
.row
  %strong Id:
  = @transaction.id
.row
  %strong Amount:
  = @transaction.amount
.row
  %strong Description:
  = @transaction.description
.row
  %strong Transaction purpose:
  = @transaction.transaction_purpose.name
.row
  %strong Transfer:
  = @transaction.transfer.name
.row
  %strong Created at:
  = @transaction.created_at
.row
  %strong Updated at:
  = @transaction.updated_at
.row
  = link_to_edit(@transaction)
  = close_reveal_button

app/views/transactions/success.js.erb
<%- if params[:action] == 'create' %>
  if($('<%= ".#{params[:transaction][:unique_id]}" %>' + ' select[name="transaction[transaction_purpose_id]"]').length) {
    $('<%= ".#{params[:transaction][:unique_id]}" %>').before("<%=j render 'home/transaction_form', transaction: new_transaction, transacted_at: transacted_at %>");
  }
<%- end %>
$('<%= ".#{params[:transaction][:unique_id]}" %>').prev('.flash-message').remove();
$('<%= ".#{params[:transaction][:unique_id]}" %>').before('<%=j flash_messages %>');
$('<%= ".#{params[:transaction][:unique_id]}" %>').replaceWith("<%=j render 'home/transaction_form', transaction: transaction, transacted_at: transacted_at %>");